### ISSUE TITLE
Create manufacturer delete page in admin part

### ISSUE THREAD

**Issue by fergus-macdubh** [neodoc1976/jylishop#30]
Create manufacturer delete page in admin part

**Comment by fergus-macdubh** [comment]
Note, that manufacturer cannot be deleted, if it is used somewhere. So, you should handle that case correctly. Possible ways:
1. Check if some product use that manufacturer and show message to user about that. Do not try to delete from DB.
2. Try to delete it and in case of exception - show message.
3. Try to find all products with this manufacturer and delete them.
4. Try to find all products with this manufacturer and reassign them to 'NoName' or other default value.

Feel free to choose any and write it down in a comment. Then go ahead with implementation.

**Comment by neodoc1976** [comment]
Simply Delete method for Manufacturer is added.

**Comment by neodoc1976** [comment]
Full method for Delete\Change Manufacturer is added.
