### ISSUE TITLE
Валидация ID товаров

### ISSUE THREAD

**Issue by fergus-macdubh** [neodoc1976/jylishop#5]
При добавлении любого товара нужно проверить нет ли уже товара с таким ID в базе данных. В случае, если есть, отобразить страницу с сообщением об ошибке.

**Comment by neodoc1976** [comment]
Done

**Comment by fergus-macdubh** [comment]
Where is the commit?

**Comment by neodoc1976** [comment]
Excuse me, are sent.

**Comment by fergus-macdubh** [comment]
Does this really work?
I didn't check out the code and run, but it seems that your code produces NullPointerException in invalid case.
